/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx,ts,tsx}'],
  darkMode: 'class',
  theme: {
    fontFamily: {
      sans:    ['Public Sans', 'system-ui', 'sans-serif'],
      heading: ['Hanken Grotesk', 'system-ui', 'sans-serif'],
      serif:   ['Instrument Serif', 'Georgia', 'serif'],
      mono:    ['ui-monospace', 'Consolas', 'monospace'],
    },
    extend: {
      colors: {
        // Brand constants — never change between themes
        'midnight-mirage':    '#001F3F',
        'nuit-blanche':       '#1E488F',
        'accent-hover':       '#163A73',
        'mantis':             '#74C365',
        'picture-book-green': '#00804C',
        'praxeti-white':      '#F6F7ED',
        complement:           '#DBE64C',
        'on-primary':         '#ffffff',
        error:                'var(--hl-error)',
        'error-container':    'var(--hl-error-container)',
        'on-error':           '#ffffff',
        success:              '#00804C',
        'success-light':      '#74C365',

        // Semantic tokens — switch between light and dark via CSS vars
        primary:                    'var(--hl-primary)',
        'primary-container':        'var(--hl-primary-container)',
        'on-primary-container':     'var(--hl-on-primary-container)',
        secondary:                  'var(--hl-secondary)',
        'on-secondary':             '#ffffff',
        'secondary-container':      'var(--hl-secondary-container)',
        'on-secondary-container':   'var(--hl-on-secondary-container)',
        tertiary:                   'var(--hl-tertiary)',
        'on-tertiary':              '#ffffff',
        'tertiary-container':       'var(--hl-tertiary-container)',
        'on-tertiary-container':    'var(--hl-on-tertiary-container)',
        surface:                    'var(--hl-surface)',
        'surface-dim':              'var(--hl-surface-dim)',
        'surface-bright':           'var(--hl-surface-bright)',
        'surface-container-lowest': 'var(--hl-surface-container-lowest)',
        'surface-container-low':    'var(--hl-surface-container-low)',
        'surface-container':        'var(--hl-surface-container)',
        'surface-container-high':   'var(--hl-surface-container-high)',
        'surface-container-highest':'var(--hl-surface-container-highest)',
        'on-surface':               'var(--hl-on-surface)',
        'on-surface-variant':       'var(--hl-on-surface-variant)',
        outline:                    'var(--hl-outline)',
        'outline-variant':          'var(--hl-outline-variant)',
        background:                 'var(--hl-surface)',
        'on-background':            'var(--hl-on-surface)',
        'surface-dark':             '#002B56',
      },
      fontSize: {
        'page-title':         ['1.6rem',  { lineHeight: '2.4rem',    fontWeight: '700' }],
        'headline-lg':        ['2rem',    { lineHeight: '3rem',      fontWeight: '600' }],
        'headline-lg-mobile': ['1.5rem',  { lineHeight: '2.25rem',   fontWeight: '600' }],
        'headline-md':        ['1.25rem', { lineHeight: '1.875rem',  fontWeight: '600' }],
        'headline-md-mobile': ['1.1rem',  { lineHeight: '1.65rem',   fontWeight: '600' }],
        'section-head':       ['1rem',    { lineHeight: '1.5rem',    fontWeight: '700' }],
        'body-lg':            ['1rem',    { lineHeight: '1.5rem',    fontWeight: '400' }],
        'body-md':            ['0.95rem', { lineHeight: '1.6125rem', fontWeight: '400' }],
        'label-sm':           ['0.85rem', { lineHeight: '1.25rem',   fontWeight: '600' }],
        meta:                 ['0.8rem',  { lineHeight: '1.1875rem', fontWeight: '500' }],
      },
      spacing: {
        'grid-base':    '8px',
        xs:             '4px',
        sm:             '8px',
        md:             '16px',
        lg:             '24px',
        xl:             '32px',
        gutter:         '24px',
        'card-padding': '24px',
        'page-margin':  '32px',
      },
      borderRadius: {
        sm:      '0.25rem',
        DEFAULT: '0.5rem',
        md:      '0.75rem',
        lg:      '1rem',
        xl:      '1.5rem',
        full:    '9999px',
      },
      boxShadow: {
        card:    '0 2px 12px rgba(0,0,0,0.08)',
        modal:   '0 12px 48px rgba(0,0,0,0.18)',
        sidebar: '2px 0 8px rgba(0,0,0,0.06)',
      },
      transitionTimingFunction: {
        spring: 'cubic-bezier(0.16, 1, 0.3, 1)',
      },
    },
  },
  plugins: [],
}
